config/routes.rb
Rails.application.routes.draw do
  get 'sermons/index'

  get 'sermons/show'

  get 'sermons/new'

  get 'sermons/create'

  get 'sermons/edit'

  get 'sermons/update'

  devise_for :users
   root  'grace_finals#home'
  get  'im_new'    => 'grace_finals#im_new'
  get  'know_us'    => 'grace_finals#know_us'
  get  'what_we_do'    => 'grace_finals#what_we_do'
  get  'resources' => 'grace_finals#resources'
  get  'contribute'    => 'grace_finals#contribute'
  get  'contact'    => 'grace_finals#contact'

  #resources
  get  'sermon_series'    => 'grace_finals#sermon_series'
  get  'app'    => 'grace_finals#app'
  get  'books'    => 'grace_finals#books'


#faith statement 
  get  'statement_of_faith'    => 'grace_finals#statement_of_faith'

  #sunday
   get  'sunday'    => 'grace_finals#sunday'

   #grace_stories
   get  'grace_stories'    => 'grace_finals#grace_stories'

   #grace_stories
   get  'volunteer'    => 'grace_finals#volunteer'

    #community_group
   get  'community_groups'    => 'grace_finals#community_groups'

   #create
   get  'create'    => 'grace_finals#create'

   #dna_group
   get  'dna'    => 'grace_finals#dna'

   #serve
   get  'serve'    => 'grace_finals#serve'

resources :users, only: [:show]
resources :events 
resources :sermons
resources :photos 
resources :groups
resources :audios



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :fullname, presence: true, length: {maximum: 50}

  has_many :events
  has_many :reservations
  has_many :sermons
  has_many :groups

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :dashboard]
  before_action :find_episode, only: [:show, :dashboard]

  def index
    @users = User.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 12)
  end

  def show
     @user = User.find(params[:id])
    @events = @user.events
    @sermons = @user.sermons
  end

  def dashboard
  end

  private

  def find_episode
    @episodes = Episode.where(user_id: @user).order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  def find_user
    if params[:id].nil?
      @user = current_user
    else
      @user = User.find(params[:id])
    end
  end
end
  

app/views/users/dashboard.html.erb
<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
      <h1><%= @user.title %></h1>
    </div>
  </div>

  <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li class="current">Episodes</li>
        <li><%= link_to "New Episode", new_user_episode_path(@user) %></li>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <li><%= link_to "View Podcast", user_path(current_user) %></li>
      </ul>
    </div>
  </div>

  <div id="episodes">
    <div class="wrapper_skinny">
      <ul class="cf">
        <% @episodes.each do |episode| %>
          <li class="cf">
            <div class="episode_thumbnail">
              <a href="#">
                <%= image_tag episode.episode_thumbnail.url(:medium) %>
              </a>
            </div>
            <div class="episode_overview">
              <h2><%= link_to episode.title, user_episode_path(@user, episode) %></h2>
              <p class="description"><%= truncate(episode.description, lenght: 160) %></p>
              <div class="authorized_links">
                <%= link_to "Edit", edit_user_episode_path(@user, episode) %>
                <%= link_to "Delete", user_episode_path(@user, episode), method: :delete, data: {confirm: "Are you sure?"} %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>

      <%= will_paginate @episodes, previous_label: "Previous", next_label: "Next" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div id="banner" class="podcasts_banner">
  <h1>Discover your new favorite User</h1>
</div>

<div id="podcasts" class="cf">
  <div class="wrapper">
    <ul class="cf">
      <% @users.each do |user| %>
        <%= link_to user do %>
          <li>
            <%= image_tag user.thumbnail.url(:medium) %>
            <div class="podcast_overview">
              <h2><%= user.title %></h2>
              <p class="episode_count">1 Episode</p>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>

    <%= will_paginate @users, previous_label: "Previous", next_label: "Next" %>
  </div>
</div>

    

app/views/users/show.html.erb
<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
      <h1><%= @user.title %></h1>
      <p class="description"><%= @user.description %></p>
      <% unless @user.itunes.blank? %>
        <a href="<%= @podcast.itunes %>" class="subscribe_link">iTunes</a>
      <% end %>
      <% unless @user.stitcher.blank? %>
        <a href="<%= @podcast.stitcher %>" class="subscribe_link">Stitcher</a>
      <% end %>
      <% unless @user.podbay.blank? %>
        <a href="<%= @podcast.podbay %>" class="subscribe_link">PodBay</a>
      <% end %>
    </div>
  </div>

  <div id="breadcrumb">
    <%= link_to users_path do %>
      All Users
      <span>/</span>
      <%= @user.title %>
    <% end %>
  </div>

  <div id="episodes">
    <div class="wrapper_skinny">
      <ul class="cf">
        <% @episodes.each do |episode| %>
          <li class="cf">
            <div class="episode_thumbnail">
              <a href="#">
                <%= image_tag episode.episode_thumbnail.url(:medium) %>
              </a>
            </div>
            <div class="episode_overview">
              <h2><%= link_to episode.title, user_episode_path(@user, episode) %></h2>
              <p class="description"><%= truncate(episode.description, length: 160) %></p>
            </div>
          </li>
        <% end %>
      </ul>

      <%= will_paginate @episodes, previous_label: "Previous", next_label: "Next" %>
    </div>
  </div>
</div>