config/routes.rb
Rails.application.routes.draw do
  get 'sermons/index'

  get 'sermons/show'

  get 'sermons/new'

  get 'sermons/create'

  get 'sermons/edit'

  get 'sermons/update'

  devise_for :users
   root  'grace_finals#home'
  get  'im_new'    => 'grace_finals#im_new'
  get  'know_us'    => 'grace_finals#know_us'
  get  'what_we_do'    => 'grace_finals#what_we_do'
  get  'resources' => 'grace_finals#resources'
  get  'contribute'    => 'grace_finals#contribute'
  get  'contact'    => 'grace_finals#contact'

  #resources
  get  'sermon_series'    => 'grace_finals#sermon_series'
  get  'app'    => 'grace_finals#app'
  get  'books'    => 'grace_finals#books'


#faith statement 
  get  'statement_of_faith'    => 'grace_finals#statement_of_faith'

  #sunday
   get  'sunday'    => 'grace_finals#sunday'

   #grace_stories
   get  'grace_stories'    => 'grace_finals#grace_stories'

   #grace_stories
   get  'volunteer'    => 'grace_finals#volunteer'

    #community_group
   get  'community_groups'    => 'grace_finals#community_groups'

   #create
   get  'create'    => 'grace_finals#create'

   #dna_group
   get  'dna'    => 'grace_finals#dna'

   #serve
   get  'serve'    => 'grace_finals#serve'

resources :users, only: [:show]
resources :events 
resources :sermons
resources :photos 
resources :groups
resources :audios



end

app/views/shared/_footer.html.erb
<!-- Page sections end. -->
  <a name="footer-v2"></a>
    
    <!-- ========== Footer Widgets ========== -->
    <div class="widget-foot-wrap bg-smoke">
        <div class="container">
            <div class="row">
    
                <!-- /Footer Col 1 -->
                <!-- Footer Col 2 -->
                <div class="col-md-4">
                    <div class="widget-foot">
                        <h4 class="title underline">Churches</h4>
                        <div class="body">
                            <ul class="widget-nav widget-nav-archive">
                            <li><a href="/">Community of Grace East Queens</a></li>
                            <li><a href="www.gracenyc.org/">Community of Grace Upper West Side</a></li>
                           </ul>
                        </div>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="widget-foot">
                        <h4 class="title underline">Contact Us</h4>
                        <div class="body">
                            <ul class="contact-list-icon">
                                <li><i class="fa fa-map-marker"></i>61-35 220TH STREET OAKLAND GARDENS, NY 11364</li>
                                <li><i class="fa fa-phone"></i>+347.817.7986</li>
                                <li><i class="fa fa-envelope"></i>INFO@GRACENYC.ORG</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /Footer Col 3 -->
                
                <!-- /Footer Col 2 -->
                <!-- Footer Col 3 -->
                <div class="col-md-2">
                    <div class="widget-foot">
                        <h4 class="title underline">Connect With Us</h4>
                        <div class="body">
                            <a href="#" class="btn btn-social-icon btn-facebook"><i class="fa fa-facebook"></i></a>
                            <a href="#" class="btn btn-social-icon btn-google"><i class="fa fa-google"></i></a><br /><div style="height:3px"></div>
                        </div>
                    </div>
                </div>
                <!-- /Footer Col 3 -->
                <!-- Footer Col 4 -->
                 <div class="col-md-3">
                    <div class="widget-foot">
                        <h4 class="title underline">PARTNERS</h4>
                        <div class="body">
                           <ul class="widget-nav widget-nav-archive">
                            <li><h5><a href="http://www.acts29.com/" target = "_blank">Acts 29</a></h5></li>
                            <li><h5><a href="https://www.redeemercitytocity.com/"  target = "_blank">Redeemer City to City</a></h5></li>
                            </ul>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ========== /Footer Widgets ========== -->    
    
    <!-- ========== Footer Nav and Copyright ========== -->
    <div id="footers">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="copyright">Copyright 2017 CommunityofGraceEastQueens.com<br />All Rights Reserved</div>
                </div>
            </div>
        </div>
    </div>
    <!-- ========== /Footer Nav and Copyright ========== -->    

app/views/shared/_javascript.html.erb
      <!-- jQuery -->
    <script type="text/javascript" src="assets/grace_final/jquery-1.10.2.min.js"></script>

    <!-- Needed for Video/Image Slider/Banners -->
    <script type="text/javascript" src="assets/grace_final/video.js"></script>
    <script type="text/javascript" src="assets/grace_final/bigvideo.js"></script>

    <!-- Bootstrap -->
    <script type="text/javascript" src="assets/grace_final/bootstrap.min.js"></script>

    <!-- Plugins -->
    <script type="text/javascript" src="assets/grace_final/modernizr-2.6.2.min.js"></script>
    <script type="text/javascript" src="assets/grace_final/imagesloaded.pkgd.min.js"></script>
    <script type="text/javascript" src="assets/grace_final/isotope.pkgd.min.js"></script>
    <script type="text/javascript" src="assets/grace_final/jquery.smartmenus.min.js"></script>
    <script type="text/javascript" src="assets/grace_final/jquery.smartmenus.bootstrap.min.js"></script>
    <script type="text/javascript" src="assets/grace_final/scrollReveal.js"></script>
    <script type="text/javascript" src="assets/grace_final/jquery.magnific-popup.js"></script>
    
    <!-- Switcher - DEMO ONLY --->
    <script src="switcher/js/dmss.js"></script>

    

    <!-- Custom JS -->
    <script type="text/javascript" src="assets/grace_final/magnet-main.js"></script>
    <script type="text/javascript" src="assets/grace_final/carousel-animations.js"></script>

  
    
    <script>
    var config = {
        reset:  false,
        delay:  'onload',
        vFactor: 0.90,
        mobile: false
    }
    window.sr = new scrollReveal(config);
    $('.gallery-link').magnificPopup({
        type: 'image',
        gallery:{enabled:true}
    });
    </script>

app/views/shared/_navbar.html.erb
 <!-- ========== Navbar ========== -->
    <div class="navbar navbar-magnet navbar-fixed-top" role="navigation" id="navbar-main-magnet">
        <div class="container">
            
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><i class="fa fa-bars"></i></button>
               
                
                <!-- Logo -->
                <a class="navbar-brand" href="/"><img src="assets/grace_final/logo.png" alt=" East Queens" /></a>
                <!-- /Logo -->
            </div>
            
            <!-- Navigation -->
            <div class="navbar-collapse collapse">
            <% if(!user_signed_in?) %>
                <ul class="nav navbar-nav navbar-right">
                    <!-- Home -->
                    <li>
                   <li><%= link_to "Home", root_path %></li>
                    </li>
                    <li>
                   <li><%= link_to "I'm New", im_new_path %></li>
                    </li>
                    <li>
                   <li><%= link_to "Get to know us", know_us_path %></li>
                    </li>
                    <li>
                   <li><%= link_to "What we do", what_we_do_path %></li>
                    </li>
                     <li>
                     <li>
                    <li><%= link_to "Events", events_path %></li>
                    </li>
                    <li>
                   <li><%= link_to "Resources", resources_path %></li>
                    </li>
                     <li>
                   <li><%= link_to "Contribute", contribute_path %></li>
                    </li>
                     <li>
                   <li><%= link_to "Contact", contact_path %></li>
                    </li>
                </ul>
                <% else %>
                 <ul class="nav navbar-nav navbar-right">
                    <!-- Home -->
                    <li><%= link_to "Home", root_path %></li>
                    
                   <li><%= link_to "Get to know us", know_us_path %></li>

                  
                   <li><%= link_to "Resources", resources_path %></li>
                    

                   
                    <li><%= link_to "Events", events_path %></li>
                    

                
                    <li><%= link_to "Create New", create_path %></li>
                    

                   
                     <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
                     
                </ul>
                 <% end %>
            </div>
            <!-- /Navigation -->
            
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- ========== /Navbar ========== -->  