config/routes.rb
Rails.application.routes.draw do
  get 'sermons/index'

  get 'sermons/show'

  get 'sermons/new'

  get 'sermons/create'

  get 'sermons/edit'

  get 'sermons/update'

  devise_for :users
   root  'grace_finals#home'
  get  'im_new'    => 'grace_finals#im_new'
  get  'know_us'    => 'grace_finals#know_us'
  get  'what_we_do'    => 'grace_finals#what_we_do'
  get  'resources' => 'grace_finals#resources'
  get  'contribute'    => 'grace_finals#contribute'
  get  'contact'    => 'grace_finals#contact'

  #resources
  get  'sermon_series'    => 'grace_finals#sermon_series'
  get  'app'    => 'grace_finals#app'
  get  'books'    => 'grace_finals#books'


#faith statement 
  get  'statement_of_faith'    => 'grace_finals#statement_of_faith'

  #sunday
   get  'sunday'    => 'grace_finals#sunday'

   #grace_stories
   get  'grace_stories'    => 'grace_finals#grace_stories'

   #grace_stories
   get  'volunteer'    => 'grace_finals#volunteer'

    #community_group
   get  'community_groups'    => 'grace_finals#community_groups'

   #create
   get  'create'    => 'grace_finals#create'

   #dna_group
   get  'dna'    => 'grace_finals#dna'

   #serve
   get  'serve'    => 'grace_finals#serve'

resources :users, only: [:show]
resources :events 
resources :sermons
resources :photos 
resources :groups
resources :audios



end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :photos,  as: :photoable, dependent: :destroy
  has_many :reservations

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :title, presence: true
  validates :description, presence: true, length: {maximum: 500}
  validates :address, presence: true
  validates :date, presence: true
  validates :time, presence: true


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @event = Event.order(:date)
    @events = Event.paginate(:page => params[:date], :per_page => 3)
  end

  def show
    @photos = @event.photos
  end

  def new
     @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save

      if params[:images] 
        params[:images].each do |image|
          @event.photos.create(image: image)
        end
      end

      @photos = @event.photos
      redirect_to edit_event_path(@event), notice: "Saved..."
    else
      render :new
    end
  end

  def edit
   if current_user.id == @event.user.id
      @photos = @event.photos
    else
      redirect_to root_path, notice: "You don't have permission."
    end
  end

  def update
    if @event.update(event_params)

      if params[:images] 
        params[:images].each do |image|
          @event.photos.create(image: image)
        end
      end

      redirect_to edit_event_path(@event), notice: "Updated..."
    else
      render :edit
    end
  end

   def destroy
    @event = Event.find(params[:id])
    @event.destroy
 
    redirect_to events_path
  end

  private

  def set_event
      @event = Event.find(params[:id])
  end

  def event_params
      params.require(:event).permit(:title, :description, :address, :date, :time)
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Create an Event
  </div>
  <div class="panel-body">
    <div class="container">
      
      <%= form_for @event, :html => { multipart: true } do |f| %>

        <div class="row">
          <div class="form-group">
            <label>Event Name</label>
            <%= f.text_field :title, placeholder: "Be clear and descriptive", class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="form-group">
            <label>Summary</label>
            <%= f.text_area :description, rows: 5, placeholder: "What is the event about?", class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="form-group">
            <label>Address</label>
            <%= f.text_field :address, placeholder: "What is the address for the event?", class: "form-control" %>
          </div>
        </div>


  <div class="row">
    <div class="col-xs-12">
      <label>Start Date</label>
      <%= f.label :date %>
      <%= f.date_select :date %>
      <%= f.label :"Time (24 Hours)" %>
      <%= f.time_select :time %>
    </div>
  </div>

        <div class="row">
          <div class="col-md-4">
            <div class="form-group">              
              <span class="btn btn-default btn-file">
                  <i class="fa fa-cloud-upload fa-lg"></i> Upload Photos 
                  <%= file_field_tag "images[]", type: :file, multiple: true %>
              </span>
            </div>    
          </div>
        </div>

        <div id="photos"><%= render 'photos/list' %></div>


        <div class="actions">
          <%= f.submit "Save", class: "btn btn-primary" %>
        </div>

      <% end %>

    </div>
  </div>
</div> 


<script>
  $(function() {

    $('#reservation_start_date').datepicker({
      dateFormat: 'dd-mm-yy'
    });
    $('#reservation_end_date').datepicker({
      dateFormat: 'dd-mm-yy'
    });

  });
</script>

 <%= render 'shared/javascript' %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
 <%= render 'shared/navbar' %>
    <!-- ========== Page Header ========== -->
                <div class="jumbotron image-banner full-screen" style="background:linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('assets/grace_final/park.png') no-repeat 0 0 #ffffff;background-size:cover;background-position:center center">
            <div class="container">
                <div class="center-block">
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                    <h1 class="text-center">Upcoming Events</h1>
                    <h3 class="text-center"></h3>
                    <div class="text-center">
                                
                            </div>
                </div><div class="helper"></div>
            </div>
        </div>
        <!-- ========== /Page Header ========== -->
               <!-- ========== Page Content ========== -->
    <div class="section bg-white">
      <div class="container">
          
  <div id="pages">
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Upcoming Events
      </div>
      <div class="panel-body">
        
        <% @event.each do |event| %>
          <div class="row">
            <div class="col-md-4">
              <%= image_tag event.photos[0].image.url(:thumb) if event.photos.length > 0 %>
            </div>    
            <div class="col-md-4">
              <h4><%= link_to event.title, event_path(event) %></h4>
            </div>  
              <div class="col-md-4">
              <h4><%= event.date.strftime(" %A, %b  %d  %Y") %> <br><%= event.time.strftime("%l:%M %p")%></h4>  
              <% if(!user_signed_in?) %>

            <% else %>
          <%= link_to "Update", edit_event_path(event), class: "btn btn-primary" %>
          <%= link_to 'Destroy', event_path(event),
              method: :delete,
              data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger'%>
          <% end %>
              </div>
          </div>
          <hr>
        <% end %>
        <div class= "text-center">
         <%= will_paginate @events %>
         </div>

      </div>
    </div>
  </div>
</div>
 </div>
  </div>
</div>

<%= render 'shared/footer' %>

 <%= render 'shared/javascript' %>

app/views/events/show.html.erb
 <%= render 'shared/navbar' %>
  <div class="section bg-white">
      <div class="container">
          
  <div id="pages">
<div class="panel panel-default">
  <div class="panel-body">
    
    <!-- Image -->
    <div class="row">
      <div class="col-md-12">
       <h1><%= @event.title %></h1>
        <%= image_tag @photos[0].image.url(), class: "img-responsive " if @photos.length > 0 %>
      </div>
    </div>

    <br>

    <!-- Main Info -->

    <!-- About -->
    <div class="row">
      <div class="col-md-4">
        <h2>About this event</h2>
        <p><%= @event.description %></p>
      </div>

      <div class="col-md-4">
        <h2>Time and Date</h2>
        <p><h4><%= @event.date.strftime(" %A, %b  %d  %Y") %> <br><%= @event.time.strftime("%l:%M %p")%></p>
      </div>

      <div class="col-md-4">
        <h2>Address</h2>
        <p><%= @event.address %></p>
      </div>
  </div>



  
    <br>
    <hr>


    <!-- Google Map -->
    <div class="row">
      <div class="col-md-12">
        
        <div id="map"></div>

        <style>
          #map {
            width: 100%;
            height: 400px;
          }
        </style>

      <script>
      function initMap() {
      var uluru = {lat: <%= @event.latitude %>, lng: <%= @event.longitude %>};
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 15,
        center: uluru
        });
      var marker = new google.maps.Marker({
        position: uluru,
        map: map
        });
        }
  </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_map_id'] %>&callback=initMap">
    </script>
      </div>
    </div>
    
  </div>
</div>
</div>
</div>
</div>


<%= render 'shared/footer' %>

 <%= render 'shared/javascript' %>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>