config/routes.rb
Rails.application.routes.draw do
  get 'sermons/index'

  get 'sermons/show'

  get 'sermons/new'

  get 'sermons/create'

  get 'sermons/edit'

  get 'sermons/update'

  devise_for :users
   root  'grace_finals#home'
  get  'im_new'    => 'grace_finals#im_new'
  get  'know_us'    => 'grace_finals#know_us'
  get  'what_we_do'    => 'grace_finals#what_we_do'
  get  'resources' => 'grace_finals#resources'
  get  'contribute'    => 'grace_finals#contribute'
  get  'contact'    => 'grace_finals#contact'

  #resources
  get  'sermon_series'    => 'grace_finals#sermon_series'
  get  'app'    => 'grace_finals#app'
  get  'books'    => 'grace_finals#books'


#faith statement 
  get  'statement_of_faith'    => 'grace_finals#statement_of_faith'

  #sunday
   get  'sunday'    => 'grace_finals#sunday'

   #grace_stories
   get  'grace_stories'    => 'grace_finals#grace_stories'

   #grace_stories
   get  'volunteer'    => 'grace_finals#volunteer'

    #community_group
   get  'community_groups'    => 'grace_finals#community_groups'

   #create
   get  'create'    => 'grace_finals#create'

   #dna_group
   get  'dna'    => 'grace_finals#dna'

   #serve
   get  'serve'    => 'grace_finals#serve'

resources :users, only: [:show]
resources :events 
resources :sermons
resources :photos 
resources :groups
resources :audios



end

app/controllers/grace_finals_controller.rb
class GraceFinalsController < ApplicationController

  def home
     @event = Event.order(:date)
     @sermon = Sermon.order(:date)
  end

  def volunteer
  end

  def create
     @event = Event.order(:date)
     @sermon = Sermon.order(:date)
     @group = Group.order(:date)
  end

  def im_new
  end

  def know_us
  end

  def what_we_do
  end

  def resources
  end

  def contact
  end

  def contribute
  end

  def sermon_series
    @sermon = Sermon.order(:date)
  end

  def app
  end

  def books
  end

  def statement_of_faith
  end

  def sunday
  end

  def community_groups
    @group = Group.order(:date)
    @groups = Group.paginate(:page => params[:date], :per_page => 3)
  end

  def dna
  end

  def serve
  end

  def grace_stories
  end

end
 

app/helpers/grace_finals_helper.rb
module GraceFinalsHelper
end

app/views/grace_finals/app.html.erb
  <%= render 'shared/navbar' %>


        </div>
        <div class="clearfix"></div>
    </div>
    <!-- ========== /Navbar ========== -->    
    <!-- Page sections start. -->
  <div id="pages">
    
        <!-- ========== Page Header ========== -->
        <div class="jumbotron">
      <div class="container">
        <h2 class="block-title">Tabs</h2>
      </div>
    </div>
        <!-- ========== /Page Header ========== -->
        
        <!-- ========== Page Content ========== -->
    <div class="section bg-white">
      <div class="container">
                    
                    
                    <div class="row">
                <div class="col-md-3">
                    
                    <!-- Shortcodes page list -->
                    <div class="list-group">
                        <a href="/resources" class="list-group-item">Resources</a>
                        <a href="/sermon_series" class="list-group-item">Sermon Series</a>
                        <a href="/app" class="list-group-item active">App</a>
                        <a href="/books" class="list-group-item">Books</a>
                    </div>
                    <!-- /Shortcodes page list -->
                </div>

                <div class="col-md-9"> 
                
                    <h2>The Community of Grace App</h2>
                    <hr />
                    <div>
                    <a href="https://itunes.apple.com/us/app/the-community-of-grace/id1072207434?ls=1&mt=8" target="blank">IPHONE APP | ANDROID APP</a>

                    <div class="col-sm-4">
                        <div class="post-grid" data-sr='wait 0.2s, scale up 30%'> 
                            <div class="image">
                                <img src="assets/grace_final/1.jpg" alt="" class="img-responsive" />
                                <div class="caption">
                                    <div class="caption-inner">
                                        <!-- <a href="images/news-2.jpg" class="icon-link white"><i class="fa fa-search"></i></a> -->
                                        <a href=href="https://itunes.apple.com/us/app/the-community-of-grace/id1072207434?ls=1&mt=8" target="blank"></a>
                                    </div>
                                    <div class="helper"></div>
                                </div>
                            </div>
                            </div>
                            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- ========== /Navbar ========== -->
</div>
</div>
  
    
    <!-- Back to Top -->
    <div id="back_to_top">
        <div class="container">
            <a href="#"><i class="ic ic-angle-up-white"></i></a>
        </div>
    </div>
    <!-- /Back to Top -->    

<%= render 'shared/footer' %>

<%= render 'shared/javascript' %>
    

app/views/grace_finals/community_groups.html.erb
<%= render 'shared/navbar' %>
  
    <!-- Page sections start. -->
        
      <!-- Page sections start. -->
        
         <!-- ========== Page Header ========== -->
                <div class="jumbotron image-banner full-screen" style="background:linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('assets/grace_final/bbq10.jpg') no-repeat 0 0 #ffffff;background-size:cover;background-position:center center">
            <div class="container">
                <div class="center-block">
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                    <h1 class="text-center">Community Group</h1>
                    <h3 class="text-center"></h3>
                    <div class="text-center">
                              
                            </div>
                </div><div class="helper"></div>
            </div>
        </div>
        <!-- ========== /Page Header ========== -->


          <!-- ========== Page Content ========== -->
        <div class="bg-white">
            <div class="container">
                <div class="featurette">
                    <h2 class="featurette-heading text-center"> Learn more about Community Groups</h2>
                    <i><p class="featurette-lead text-center"></p></i>
                    <div class="row">
                        <div class="col-md-12">
                            <p class="text-justify">DNA group refers to a group that usually consists of 3-4 people, men with men, women with women – who meet together weekly. They seek to be vulnerable and to bring gospel truths to bear on each other’s lives to move from unbelief to belief, becoming more like Jesus.</p>

                            <p class="text-justify">DNA groups learn together, grow together, and live out God-given identities in community. If you would like to join a group please email  benthariath@gmail.com  or blazinb112@gmail.com </p>
                                  
                        </div>
                         <div class="row">
                        <div class="col-md-6">
                            <img data-sr='enter top move 100px' class="featurette-image img-responsive center-block" src="assets/grace_final/bbq3.jpg" alt="Generic placeholder image">
                        </div>
                        <div class="col-md-6">
                            <div class="panel panel-default">
      <div class="panel-heading">
        <h3>Community Group Events</h3>
      </div>
      <div class="panel-body">
        
        <% @group.each do |group| %>
          <div class="row">
            <div class="col-md-4">
              <%= image_tag group.photos[0].image.url(:thumb) if group.photos.length > 0 %>
            </div>    
            <div class="col-md-4">
              <h4><%= link_to group.title, group_path(group) %></h4>
            </div>  
              <div class="col-md-4">
              <h4><%= group.date.strftime(" %A, %b  %d  %Y") %> <br><%= group.time.strftime("%l:%M %p")%></h4>  
              <% if(!user_signed_in?) %>

            <% else %>
          <%= link_to "Update", edit_group_path(group), class: "btn btn-primary" %>
          <%= link_to 'Destroy', group_path(group),
              method: :delete,
              data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger'%>
          <% end %>
              </div>
          </div>
          <hr>
        <% end %>
        <div class= "text-center">
         </div>

      </div>
    </div>
  </div>
</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


 

     <!-- Back to Top -->
    <div id="back_to_top">
        <div class="container">
            <a href="#"><i class="ic ic-angle-up-white"></i></a>
        </div>
    </div>
    <!-- /Back to Top -->    
    <%= render 'shared/footer' %>
<%= render 'shared/javascript' %>

app/views/grace_finals/contact.html.erb
  <%= render 'shared/navbar' %>
  <!-- Page sections start. -->
    
  
    <!-- ========== Page Header ========== -->
                <div class="jumbotron image-banner full-screen" style="background: url('assets/grace_final/justin_2.jpg') no-repeat 0 0 #ffffff;background-size:cover;background-position:center center">
            <div class="container">
                <div class="center-block">
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                    <h1 class="text-center">Contact</h1>
                    <h3 class="text-center">Let us know if there is anything we can help you with</h3>
                    <div class="text-center">
                                
                            </div>
                </div><div class="helper"></div>
            </div>
        </div>
        <!-- ========== /Page Header ========== -->
        
        <!-- ========== Page Content ========== -->
    <div class="section bg-white">
      <div class="container">
        <ol class="breadcrumb">
          <li><a href="/">Home</a></li>
          <li class="active">Contact Us</li>
        </ol>
        <div class="contact-layout-3">
          <div class="row">
            <div class="col-md-8">
              <h3>DIRECTIONS</h3>
              <br />
                            <!-- Google Map -->
              <div class="map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3022.6482946228184!2d-73.75932868459392!3d40.74776387932807!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c261f18686757d%3A0x85197cef06cfa2d9!2sAnibic!5e0!3m2!1sen!2sus!4v1492489217810" width="590" height="310" frameborder="0" style="border:0"></iframe>
              </div>
                            <!-- /Google Map -->
              <h6>Keep up with OUR events and news on <a href="https://www.facebook.com/GraceEastQueensLongIsland/" target="_blank">Facebook</a>
                 <!-- /Contact Form -->
                            
                            <div class="spacer" style="height:60px;"></div>
                            <div class="widget">
                                <h4 class="widget-title">CONTACT INFORMATION</h4>
                                <div class="widget-body">
                                    <ul class="contact-list-icon">
                                        <li><i class="fa fa-map-marker"></i>61-35 220th Street Oakland Gardens, NY 11364</li>
                                        <li><i class="fa fa-phone"></i>+347.817.7986</li>
                                        <li><i class="fa fa-envelope"></i>info@gracenyc.org</li>
                                    </ul>
                                </div>
                            </div>
            </div>
            <div class="col-md-4">
              <h3>EMAIL</h3>
              <br />
                            <!-- Contact Form -->
              <div class="contact-form">
                <form name="contact-form" method="post" action="">
                  <div class="form-group"><input type="text" name="full_name" class="form-control" placeholder="Full Name:" /></div>
                  <div class="form-group"><input type="email" name="email" class="form-control" placeholder="Email:" /></div>
                  <div class="form-group"><input type="tel" name="phone" class="form-control" placeholder="Phone:" /></div>
                  <div class="form-group"><textarea cols="0" rows="7" name="message" class="form-control" placeholder="Message:"></textarea></div>
                  <div class="form-action"><input type="submit" value="SUBMIT" class="btn btn-primary-magnet btn-block btn-lg-m" /></div>
                </form>
              </div>
                         
            </div>
          </div>
        </div>
      </div>
    </div>
        
        <!-- ========== /Page Content ========== -->

    <!-- Page sections end. -->
     <!-- Back to Top -->
    <div id="back_to_top">
        <div class="container">
            <a href="#"><i class="ic ic-angle-up-white"></i></a>
        </div>
    </div>
    <!-- /Back to Top -->    

    <%= render 'shared/footer' %>

 <%= render 'shared/javascript' %>

app/views/grace_finals/dna.html.erb
<%= render 'shared/navbar' %>
  
    <!-- Page sections start. -->
        
      <!-- Page sections start. -->
        
         <!-- ========== Page Header ========== -->
                <div class="jumbotron image-banner full-screen" style="background:linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('assets/grace_final/worship_team2.jpg') no-repeat 0 0 #ffffff;background-size:cover;background-position:center center">
            <div class="container">
                <div class="center-block">
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                    <h1 class="text-center">DNA</h1>
                    <h3 class="text-center"></h3>
                    <div class="text-center">
                              
                            </div>
                </div><div class="helper"></div>
            </div>
        </div>
        <!-- ========== /Page Header ========== -->

        <!-- ========== Page Content ========== -->
        <div class="bg-white">
            <div class="container">
                <div class="featurette">
                    <h2 class="featurette-heading text-center">What is DNA?</h2>
                    <i><p class="featurette-lead text-center"></p></i>
                    <div class="row">
                        <div class="col-md-12">
                            <p class="text-justify">DNA group refers to a group that usually consists of 3-4 people, men with men, women with women – who meet together weekly. They seek to be vulnerable and to bring gospel truths to bear on each other’s lives to move from unbelief to belief, becoming more like Jesus.</p>

                            <p class="text-justify">DNA groups learn together, grow together, and live out God-given identities in community. If you would like to join a group please email  benthariath@gmail.com  or blazinb112@gmail.com </p>
                                  
                        </div>
                         <div class="row">
                        <div class="col-md-6">
                            <img data-sr='enter top move 100px' class="featurette-image img-responsive center-block" src="assets/grace_final/worship_team.jpg" alt="Generic placeholder image">
                        </div>
                        <div class="col-md-6">
                            <img data-sr='enter top move 100px' class="featurette-image img-responsive center-block" src="assets/grace_final/bbq10.jpg" alt="Generic placeholder image">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


     <!-- Back to Top -->
    <div id="back_to_top">
        <div class="container">
            <a href="#"><i class="ic ic-angle-up-white"></i></a>
        </div>
    </div>
    <!-- /Back to Top -->    
    <%= render 'shared/footer' %>
<%= render 'shared/javascript' %>

app/views/grace_finals/grace_stories.html.erb
  <%= render 'shared/navbar' %>

  <!-- Page sections start. -->
  <div id="pages">
    
   <!-- ========== Page Header ========== -->
                <div class="jumbotron image-banner full-screen" style="background:linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('assets/grace_final/grace_joy.jpg') no-repeat 0 0 #ffffff;background-size:cover;background-position:center center">
            <div class="container">
                <div class="inner">
                    <h1 class="text-center">Each one of us has a story. What's your story?</h1>
                    <h3 class="text-center">Check many stories below</h3>
                    <div class="text-center">
                                <a class="gallery-link mfp-iframe btn btn-inverse" href="https://youtu.be/lXZso40lkls"><i class="fa fa-play-circle" aria-hidden="true"></i>
                                Play Video</a>
                            </div>
                </div><div class="helper"></div>
            </div>
        </div>
        <!-- ========== /Page Header ========== -->
        
        <!-- ========== Page Content ========== -->
    <div class="section bg-white">
      <div class="container">
        
                
                <!-- /Ally -->
        <div class="post-2-col">
          <div class="post-grid even">
            <h3 class="title"><a href="blog-post.html">Allison Story</a></h3>
            <div class="image"><div class="iframe-video"><<iframe src="https://player.vimeo.com/video/207236600?color=ff9933&title=0&byline=0&portrait=0" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>></iframe></div></div>
          
          
          </div>

              <!-- DEe -->
          <div class="post-grid odd">
            <h3 class="title"><a href="blog-post.html">Dheeraj Story</a></h3>
            <div class="image"><div class="iframe-video"><iframe src="https://player.vimeo.com/video/207236620?title=0&byline=0&portrait=0" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></div></div>
         
          
          </div>

            <!-- Sunil -->
          <div class="post-grid even">
            <h3 class="title"><a href="blog-post.html">Sunil Story</a></h3>
            <div class="image"><div class="iframe-video"><iframe src="https://player.vimeo.com/video/213770353?title=0&byline=0&portrait=0" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></iframe></div></div>
           
          
          </div>

            <!-- Joshua -->
           <div class="post-grid even">
            <h3 class="title"><a href="blog-post.html">Joshua Story</a></h3>
            <div class="image"><div class="iframe-video"><iframe src="https://player.vimeo.com/video/213770528?title=0&byline=0&portrait=0" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></div></div>
       
           
          </div>
          
          <!-- Justin-->
          <div class="post-grid odd">
            <h3 class="title"><a href="blog-post.html">Justin Story</a></h3>
            <div class="image"><div class="iframe-video"><iframe src="https://player.vimeo.com/video/213770559?title=0&byline=0&portrait=0" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></div></div>
            
          </div>

          </div>
          <div class="clearfix"></div>
        </div>
                
                
      </div>
            
    </div>
        <!-- ========== /Page Content ========== -->
        
    </div>
    <!-- Page sections end. -->

<%= render 'shared/footer' %>
 <%= render 'shared/javascript' %>

app/views/grace_finals/resources.html.erb
  <%= render 'shared/navbar' %>


        </div>
        <div class="clearfix"></div>
    </div>
    <!-- ========== /Navbar ========== -->    
    <!-- Page sections start. -->
  <div id="pages">
    
        <!-- ========== Page Header ========== -->
        <div class="jumbotron">
      <div class="container">
        <h2 class="block-title">Resources</h2>
      </div>
    </div>
        <!-- ========== /Page Header ========== -->
        
        <!-- ========== Page Content ========== -->
    <div class="section bg-white">
      <div class="container">
        <div class="row">
                <div class="col-md-3">
                    <!-- Shortcodes page list -->
                    <div class="list-group">
                        <a href="/resources" class="list-group-item active ">Resources</a>
                        <a href="/sermon_series" class="list-group-item ">Sermon Series</a>
                        <a href="/app" class="list-group-item ">App</a>
                        <a href="/books" class="list-group-item">Books</a>
                    </div>
                    <!-- /Shortcodes page list -->
                </div>

                <div class="col-md-9"> 
                
                    <h2>Resources</h2>
                    <hr />
                    <!-- ========== Page Content ========== -->
    <div class="bg-white">
      <div class="container">
                <div class="featurette">
          
          <div class="row">
            <div class="col-md-12">
              <h1 class="text-center">Click any of the links to your left to see all the different resources, here at the Community of Grace we provide.</h1>
            </div>
          </div>
                </div>
      </div>
    </div>
                </div>
        </div>
        </div>
        </div>

 <!-- Back to Top -->
    <div id="back_to_top">
        <div class="container">
            <a href="#"><i class="ic ic-angle-up-white"></i></a>
        </div>
    </div>
    <!-- /Back to Top -->    

    <%= render 'shared/footer' %>
<%= render 'shared/javascript' %>
    

app/views/grace_finals/sermon_series.html.erb
  <%= render 'shared/navbar' %>


        </div>
        <div class="clearfix"></div>
    </div>
    <!-- ========== /Navbar ========== -->    
    <!-- Page sections start. -->
  <div id="pages">
    
        <!-- ========== Page Header ========== -->
        <div class="jumbotron">
      <div class="container">
        <h2 class="block-title">Tabs</h2>
      </div>
    </div>
        <!-- ========== /Page Header ========== -->
        
        <!-- ========== Page Content ========== -->
    <div class="section bg-white">
      <div class="container">
                    
                    
                    <div class="row">
                <div class="col-md-3">
                    
                    <!-- Shortcodes page list -->
                    <div class="list-group">
                        <a href="/resources" class="list-group-item">Resources</a>
                        <a href="/sermon_series" class="list-group-item active">Sermon Series</a>
                        <a href="/app" class="list-group-item">App</a>
                        <a href="/books" class="list-group-item">Books</a>
                    </div>
                    <!-- /Shortcodes page list -->
                </div>

                <div class="col-md-9"> 
                
                    <h2>Sermon Series</h2>
                    <hr />
                    <div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- ========== /Navbar ========== -->    
    <!-- Page sections start. -->
  <div id="pages">
    
        <!-- ========== Page Header ========== -->
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Sermons
      </div>
      <div class="panel-body">
        
        <% @sermon.each do |sermon| %>
          <div class="row">    
            <div class="col-md-6 text-center">
              <h2><%= link_to sermon.title, sermon_path(sermon) %></h2>
            </div>  
              <div class="col-md-4">
              <h4><%= sermon.date.strftime(" %A, %b  %d  %Y") %> <br><%= sermon.time.strftime("%l:%M %p")%></h4>  
              <% if(!user_signed_in?) %>

            <% else %>
          <%= link_to "Update", edit_sermon_path(sermon), class: "btn btn-primary" %>
          <%= link_to 'Destroy', sermon_path(sermon),
              method: :delete,
              data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger'%>
          <% end %>
              </div>
          </div>
          <hr>
        <% end %>
        <div class= "text-center">
       
         </div>

      </div>
    </div>
  </div>
</div>
 </div>
  </div>
</div>

    
    <!-- Back to Top -->
    <div id="back_to_top">
        <div class="container">
            <a href="#"><i class="ic ic-angle-up-white"></i></a>
        </div>
    </div>
    <!-- /Back to Top -->    
<%= render 'shared/footer' %>

<%= render 'shared/javascript' %>
    

app/views/grace_finals/serve.html.erb
<%= render 'shared/navbar' %>
  
    <!-- Page sections start. -->
        
      <!-- Page sections start. -->
        
         <!-- ========== Page Header ========== -->
                <div class="jumbotron image-banner full-screen" style="background:linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('assets/grace_final/grace_service.jpg') no-repeat 0 0 #ffffff;background-size:cover;background-position:center center">
            <div class="container">
                <div class="center-block">
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                    <h1 class="text-center">Serve</h1>
                    <h3 class="text-center"></h3>
                    <div class="text-center">
                              
                            </div>
                </div><div class="helper"></div>
            </div>
        </div>
        <!-- ========== /Page Header ========== -->

            <!-- ========== Latest News ========== -->
        <div class="section bg-white">
            <div class="container">
                
                        <!-- ========== Tagline Unit ========== -->
        
                <h2 class="text-center" data-sr='scale up 30%'><span class="light">How to get involved? </span></h2>
            
                <!-- ========== /Tagline Unit ========== -->

                
                      

                </div>
            </div>
        </div>
        <!-- ========== /Latest News ========== -->

     <!-- Back to Top -->
    <div id="back_to_top">
        <div class="container">
            <a href="#"><i class="ic ic-angle-up-white"></i></a>
        </div>
    </div>
    <!-- /Back to Top -->    
    <%= render 'shared/footer' %>
<%= render 'shared/javascript' %>

app/views/grace_finals/volunteer.html.erb
<%= render 'shared/navbar' %>
  
    <!-- Page sections start. -->
        
      <!-- Page sections start. -->
        
         <!-- ========== Page Header ========== -->
                <div class="jumbotron image-banner full-screen" style="background:linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('assets/grace_final/grace.jpg') no-repeat 0 0 #ffffff;background-size:cover;background-position:center center">
            <div class="container">
                <div class="center-block">
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                    <h1 class="text-center">Volunteer</h1>
                    <h3 class="text-center"></h3>
                    <div class="text-center">
                                <a class="gallery-link mfp-iframe btn btn-primary-magnet" href="https://vimeo.com/207233999" ><i class="fa fa-play-circle">
                                Play Video</a></i>
                            </div>
                </div><div class="helper"></div>
            </div>
        </div>
        <!-- ========== /Page Header ========== -->
        <!-- ========== /Page Header ========== -->

         <!-- ========== Page Content ========== -->
        <div class="bg-white">
            <div class="container">
                <div class="featurette">
                    <h2 class="featurette-heading">Volunteer</h2>
                    <i><p class="featurette-lead">Then say to him, ‘The Lord, the God of the Hebrews, <br>has sent me to say to you: Let my people go, <br>so that they may worship me in the wilderness.
                    Exodus 7:16</p></i>
                    <div class="row">
                        <div class="col-md-7">
                            <p class="text-justify">Much you see on Sunday doesn't happen without the help of many of our devoted volunteers.If you would like to help with our kids church, set up team, music, reading or scripture and our hospitality team please contact  justin.cherian07@gmail.com </p>
                                   <p><a href="https://www.google.com/maps/place/Anibic/@40.7477679,-73.7593287,17z/data=!3m1!4b1!4m5!3m4!1s0x89c261f18686757d:0x85197cef06cfa2d9!8m2!3d40.7477639!4d-73.75714" target= "_blank" class="btn btn-inverse ">Directions to Church</a>
                        </div>
                        <div class="col-md-5">
                            <img data-sr='enter top move 100px' class="featurette-image img-responsive center-block" src="assets/grace_final/grace_service.png" alt="Generic placeholder image">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfS0U7hTY7964x9wuvPmmXdxjNk5bzgjTXUeqg0GToOhAjRTQ/viewform?embedded=true" width="100%" height="100%" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
        
    </div>
    <!-- Page sections end. -->
    

         <!-- Back to Top -->
    <div id="back_to_top">
        <div class="container">
            <a href="#"><i class="ic ic-angle-up-white"></i></a>
        </div>
    </div>
    <!-- /Back to Top -->    

<%= render 'shared/footer' %>

 <%= render 'shared/javascript' %>